# Use this docker-compose if there is a local (or a remote one) MySQL database
version: "3.3"
services:
  backend:
    image: weatherapp/backend
    ports: 
      - 8080:8080
    environment: 
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=weatherapp_db
      - DATABASE_USER=weatherapp_db_user
      - DATABASE_PASSWORD=weatherAppDB_pwd
      - TOKEN_HEADER=Authorization
      - TOKEN_EXPIRATION=
      - DARKSKY_API_KEY=
    # To be further configured